#HotIf currentLayer = "Sym-D"
; ====================================== LETTERS ======================================
q::multiLongPress("q", "{Blind}~", "{Blind}°", 1, 350)
+q::multiLongPress("q", "{Blind+}°", "{Blind+}~", 1, 350)
q up::toggleLayer(previousLayer)
+q up:: toggleLayer(previousLayer)
w::multiLongPress("w", "{Blind}<", "{Blind}@", 1, 350)
+w::multiLongPress("w", "{Blind+}@", "{Blind+}<", 1, 350)
w up::toggleLayer(previousLayer)
+w up:: toggleLayer(previousLayer)
e::multiLongPress("e", "{Blind}[", "{Blind}%", 1, 350)
+e::multiLongPress("e", "{Blind+}%", "{Blind+}[", 1, 350)
e up::toggleLayer(previousLayer)
+e up:: toggleLayer(previousLayer)
r::multiLongPress("r", "{Blind}\", "{Blind}{^}", 1, 350)
+r::multiLongPress("r", "{Blind+}{^}", "{Blind+}\", 1, 350)
r up::toggleLayer(previousLayer)
+r up:: toggleLayer(previousLayer)
t::multiLongPress("t", "{Blind}—", "{Blind}–", 1, 350)
+t::multiLongPress("t", "{Blind+}–", "{Blind+}—", 1, 350)
t up::toggleLayer(previousLayer)
+t up:: toggleLayer(previousLayer)
y::multiLongPress("y", "{Blind}{U+00AB}", "{Blind}{U+00BB}", 1, 350)
+y::multiLongPress("y", "{Blind+}{U+00BB}", "{Blind+}{U+00AB}", 1, 350)
y up::toggleLayer(previousLayer)
+y up:: toggleLayer(previousLayer)
u::multiLongPress("u", "{Blind}/", "{Blind}{Numpad1}", 1, 350)
+u::multiLongPress("u", "{Blind+}{Numpad1}", "{Blind+}/", 1, 350)
u up::toggleLayer(previousLayer)
+u up:: toggleLayer(previousLayer)
i::multiLongPress("i", "{Blind}]", "{Blind}{Numpad2}", 1, 350)
+i::multiLongPress("i", "{Blind+}{Numpad2}", "{Blind+}]", 1, 350)
i up::toggleLayer(previousLayer)
+i up:: toggleLayer(previousLayer)
o::multiLongPress("o", "{Blind}>", "{Blind}{Numpad3}", 1, 350)
+o::multiLongPress("o", "{Blind+}{Numpad3}", "{Blind+}>", 1, 350)
o up::toggleLayer(previousLayer)
+o up:: toggleLayer(previousLayer)

a::multiLongPress("a", "{Blind}{{}", "{Blind}``", 1, 350)
+a::multiLongPress("a", "{Blind+}``", "{Blind+}{{}", 1, 350)
a up::toggleLayer(previousLayer)
+a up:: toggleLayer(previousLayer)
s::multiLongPress("s", "{Blind}(", "{Blind}$", 1, 350)
+s::multiLongPress("s", "{Blind+}$", "{Blind+}(", 1, 350)
s up::toggleLayer(previousLayer)
+s up:: toggleLayer(previousLayer)
d::multiLongPress("d", "{Blind+}.", "{Blind+}:", 1, 350)
+d::multiLongPress("d", "{Blind}:", "{Blind}.", 1, 350)
d up::toggleLayer(previousLayer)
+d up:: toggleLayer(previousLayer)
f::multiLongPress("f", "{Blind+},", "{Blind+};", 1, 350)
+f::multiLongPress("f", "{Blind};", "{Blind},", 1, 350)
f up::toggleLayer(previousLayer)
+f up:: toggleLayer(previousLayer)
g::multiLongPress("g", "{Blind}=", "{Blind}?", 1, 350)
+g::multiLongPress("g", "{Blind+}?", "{Blind+}=", 1, 350)
g up::toggleLayer(previousLayer)
+g up:: toggleLayer(previousLayer)
h::multiLongPress("h", "{Blind}{+}", "{Blind}{!}", 1, 350)
+h::multiLongPress("h", "{Blind+}{!}", "{Blind+}{+}", 1, 350)
h up::toggleLayer(previousLayer)
+h up:: toggleLayer(previousLayer)
j::multiLongPress("j", "{Blind}-", "{Blind}{Numpad4}", 1, 350)
+j::multiLongPress("j", "{Blind+}{Numpad4}", "{Blind+}-", 1, 350)
j up::toggleLayer(previousLayer)
+j up:: toggleLayer(previousLayer)
k::multiLongPress("k", "{Blind}`"", "{Blind}{Numpad5}", 1, 350)
+k::multiLongPress("k", "{Blind+}{Numpad5}", "{Blind+}`"", 1, 350)
k up::toggleLayer(previousLayer)
+k up:: toggleLayer(previousLayer)
l::multiLongPress("l", "{Blind})", "{Blind}{Numpad6}", 1, 350)
+l::multiLongPress("l", "{Blind+}{Numpad6}", "{Blind+})", 1, 350)
l up::toggleLayer(previousLayer)
+l up:: toggleLayer(previousLayer)
`;::multiLongPress(";", "{Blind}{}}", "{Blind}{Numpad0}", 1, 350)
+;::multiLongPress(";", "{Blind+}{Numpad0}", "{Blind+}{}}", 1, 350)
`; up::{
    if(A_PriorHotkey != ";"){
        toggleLayer(previousLayer)
    }
}
+; up::{
    if(A_PriorHotkey != ";"){
        toggleLayer(previousLayer)
    }
}

x::multiLongPress("x", "{Blind}€", "{Blind}©", 1, 350)
+x::multiLongPress("x", "{Blind+}©", "{Blind+}€", 1, 350)
x up::toggleLayer(previousLayer)
+x up:: toggleLayer(previousLayer)
c::multiLongPress("c", "{Blind}&", "{Blind}|", 1, 350)
+c::multiLongPress("c", "{Blind+}|", "{Blind+}&", 1, 350)
c up::toggleLayer(previousLayer)
+c up:: toggleLayer(previousLayer)
v::multiLongPress("v", "{Blind}{#}", "{Blind}*", 1, 350)
+v::multiLongPress("v", "{Blind+}*", "{Blind+}{#}", 1, 350)
v up::toggleLayer(previousLayer)
+v up:: toggleLayer(previousLayer)
b::multiLongPress("b", "{Blind}¿", "{Blind}¡", 1, 350)
+b::multiLongPress("b", "{Blind+}¡", "{Blind+}¿", 1, 350)
b up::toggleLayer(previousLayer)
+b up:: toggleLayer(previousLayer)
n::multiLongPress("n", "{Blind}_", "{Blind}{Numpad7}", 1, 350)
+n::multiLongPress("n", "{Blind+}{Numpad7}", "{Blind+}_", 1, 350)
n up::toggleLayer(previousLayer)
+n up:: toggleLayer(previousLayer)
m::multiLongPress("m", "{Blind}'", "{Blind}{Numpad8}", 1, 350)
+m::multiLongPress("m", "{Blind+}{Numpad8}", "{Blind+}'", 1, 350)
m up::toggleLayer(previousLayer)
+m up:: toggleLayer(previousLayer)
,::multiLongPress(",", "{Blind}§", "{Blind}{Numpad9}", 1, 350)
+,::multiLongPress("<", "{Blind+}{Numpad9}", "{Blind+}§", 1, 350)
, up::toggleLayer(previousLayer)
+, up:: toggleLayer(previousLayer)
.::multiLongPress(".", "{Blind}¶", "{Blind}™", 1, 350)
+.::multiLongPress(">", "{Blind+}™", "{Blind+}¶", 1, 350)
. up::toggleLayer(previousLayer)
+. up:: toggleLayer(previousLayer)
; ====================================== ADDITIONAL KEYS ======================================
CapsLock::toggleLayer("Ext")
*Shift::modTap(ThisHotkey, "Shift", "Shift", toggleLayer, "Sym")
*LAlt::modTapAlt(ThisHotkey, "LAlt", "Alt", toggleLayer, "Directory")
*RAlt::modTap(ThisHotkey, "RAlt", "Control", toggleLayer, previousLayer)
*'::{
    modTapAlt(ThisHotkey, "'", "RWin", SendInput, "^{BackSpace}")
    toggleLayer(previousLayer)
}