layerMatrix.Push([
; ====================================== LETTERS ======================================
; {key:"q", function:(x)=>(toggleLayers("1"))},
{key:"w", function:(x)=>(layerToggle("1"))},
{key:"e", function:(x)=>(layerToggle("2"))},
{key:"r", function:(x)=>(layerToggle("3"))},
; {key:"t", function:(x)=>(layerToggle("1"))},
; {key:"y", function:(x)=>(layerToggle("1"))},
{key:"u", function:(x)=>(layerToggle("4"))},
{key:"i", function:(x)=>(layerToggle("5"))},
{key:"o", function:(x)=>(layerToggle("6"))},
; {key:"p", function:(x)=>(layerToggle("1"))},
{key:"a", function:(x)=>(layerToggle("7"))},
{key:"s", function:(x)=>(layerToggle("8"))},
{key:"d", function:(x)=>(layerToggle("9"))},
{key:"f", function:(x)=>(layerToggle("10"))},
{key:"g", function:(x)=>(layerToggle("11"))},
{key:"h", function:(x)=>(layerToggle("12"))},
{key:"j", function:(x)=>(layerToggle("13"))},
{key:"k", function:(x)=>(layerToggle("14"))},
{key:"l", function:(x)=>(layerToggle("15"))},
{key:";", function:(x)=>(layerToggle("16"))},
; {key:"z", function:(x)=>(layerToggle("1"))},
{key:"x", function:(x)=>(layerToggle("17"))},
{key:"c", function:(x)=>(layerToggle("18"))},
{key:"v", function:(x)=>(layerToggle("19"))},
{key:"b", function:(x)=>(layerToggle("20"))},
{key:"n", function:(x)=>(layerToggle("21"))},
{key:"m", function:(x)=>(layerToggle("22"))},
{key:",", function:(x)=>(layerToggle("23"))},
])