#HotIf currentLayer = "Qwerty"
; ====================================== LETTERS ======================================
q::multiLongPress("q", "{Blind}q", "{Blind}Q", 1, 500)
+q::multiLongPress("q", "{Blind+}Q", "{Blind+}q", 1, 500)
w::multiLongPress("w", "{Blind}w", "{Blind}W", 1, 500)
+w::multiLongPress("w", "{Blind+}W", "{Blind+}w", 1, 500)
e::multiLongPress("e", "{Blind}e", "{Blind}E", 1, 500)
+e::multiLongPress("e", "{Blind+}E", "{Blind+}e", 1, 500)
r::multiLongPress("r", "{Blind}r", "{Blind}R", 1, 500)
+r::multiLongPress("r", "{Blind+}R", "{Blind+}r", 1, 500)
t::multiLongPress("t", "{Blind}t", "{Blind}T", 1, 500)
+t::multiLongPress("t", "{Blind+}T", "{Blind+}t", 1, 500)
y::multiLongPress("y", "{Blind}y", "{Blind}Y", 1, 500)
+y::multiLongPress("y", "{Blind+}Y", "{Blind+}y", 1, 500)

u::multiLongPress("u", "{Blind}{Numpad1}", "{Blind}{!}", 1, 500)
+u::multiLongPress("u", "{Blind+}{!}", "{Blind+}{Numpad1}", 1, 500)
i::multiLongPress("i", "{Blind}{Numpad2}", "{Blind}@", 1, 500)
+i::multiLongPress("i", "{Blind+}@", "{Blind+}{Numpad2}", 1, 500)
o::multiLongPress("o", "{Blind}{Numpad3}", "{Blind}{#}", 1, 500)
+o::multiLongPress("o", "{Blind+}{#}", "{Blind+}{Numpad3}", 1, 500)

p::multiLongPress("p", "{Blind}p", "{Blind}P", 1, 500)
+p::multiLongPress("p", "{Blind+}P", "{Blind+}p", 1, 500)
a::multiLongPress("a", "{Blind}a", "{Blind}A", 1, 500)
+a::multiLongPress("a", "{Blind+}A", "{Blind+}a", 1, 500)
s::multiLongPress("s", "{Blind}s", "{Blind}S", 1, 500)
+s::multiLongPress("s", "{Blind+}S", "{Blind+}s", 1, 500)
d::multiLongPress("d", "{Blind}d", "{Blind}D", 1, 500)
+d::multiLongPress("d", "{Blind+}D", "{Blind+}d", 1, 500)
f::multiLongPress("f", "{Blind}f", "{Blind}F", 1, 500)
+f::multiLongPress("f", "{Blind+}F", "{Blind+}f", 1, 500)
g::multiLongPress("g", "{Blind}g", "{Blind}G", 1, 500)
+g::multiLongPress("g", "{Blind+}G", "{Blind+}g", 1, 500)
h::multiLongPress("h", "{Blind}h", "{Blind}H", 1, 500)
+h::multiLongPress("h", "{Blind+}H", "{Blind+}h", 1, 500)

j::multiLongPress("j", "{Blind}{Numpad4}", "{Blind}$", 1, 500)
+j::multiLongPress("j", "{Blind+}$", "{Blind+}{Numpad4}", 1, 500)
k::multiLongPress("k", "{Blind}{Numpad5}", "{Blind}%", 1, 500)
+k::multiLongPress("k", "{Blind+}%", "{Blind+}{Numpad5}", 1, 500)
l::multiLongPress("l", "{Blind}{Numpad6}", "{Blind}{^}", 1, 500)
+l::multiLongPress("l", "{Blind+}{^}", "{Blind+}{Numpad6}", 1, 500)

z::multiLongPress("z", "{Blind}z", "{Blind}Z", 1, 500)
+z::multiLongPress("z", "{Blind+}Z", "{Blind+}z", 1, 500)
x::multiLongPress("x", "{Blind}x", "{Blind}X", 1, 500)
+x::multiLongPress("x", "{Blind+}X", "{Blind+}x", 1, 500)
c::multiLongPress("c", "{Blind}c", "{Blind}C", 1, 500)
+c::multiLongPress("c", "{Blind+}C", "{Blind+}c", 1, 500)
v::multiLongPress("v", "{Blind}v", "{Blind}V", 1, 500)
+v::multiLongPress("v", "{Blind+}V", "{Blind+}v", 1, 500)
b::multiLongPress("b", "{Blind}b", "{Blind}B", 1, 500)
+b::multiLongPress("b", "{Blind+}B", "{Blind+}b", 1, 500)

n::multiLongPress("n", "{Blind}{Numpad7}", "{Blind}&", 1, 500)
+n::multiLongPress("n", "{Blind+}&", "{Blind+}{Numpad7}", 1, 500)
m::multiLongPress("m", "{Blind}{Numpad8}", "{Blind}*", 1, 500)
+m::multiLongPress("m", "{Blind+}*", "{Blind+}{Numpad8}", 1, 500)
; ====================================== NUMBERS ======================================
1::multiLongPress("1", "{Blind}1", "{Blind}{!}", 1, 500)
+1::multiLongPress("1", "{Blind+}{!}", "{Blind+}1", 1, 500)
2::multiLongPress("2", "{Blind}2", "{Blind}@", 1, 500)
+2::multiLongPress("2", "{Blind+}@", "{Blind+}2", 1, 500)
3::multiLongPress("3", "{Blind}3", "{Blind}{#}", 1, 500)
+3::multiLongPress("3", "{Blind+}{#}", "{Blind+}3", 1, 500)
4::multiLongPress("4", "{Blind}4", "{Blind}$", 1, 500)
+4::multiLongPress("4", "{Blind+}$", "{Blind+}4", 1, 500)
5::multiLongPress("5", "{Blind}5", "{Blind}%", 1, 500)
+5::multiLongPress("5", "{Blind+}%", "{Blind+}5", 1, 500)
6::multiLongPress("6", "{Blind}6", "{Blind}{^}", 1, 500)
+6::multiLongPress("6", "{Blind+}{^}", "{Blind+}6", 1, 500)
7::multiLongPress("7", "{Blind}7", "{Blind}&", 1, 500)
+7::multiLongPress("7", "{Blind+}&", "{Blind+}7", 1, 500)
8::multiLongPress("8", "{Blind}8", "{Blind}*", 1, 500)
+8::multiLongPress("8", "{Blind+}*", "{Blind+}8", 1, 500)
9::multiLongPress("9", "{Blind}9", "{Blind}(", 1, 500)
+9::multiLongPress("9", "{Blind+}(", "{Blind+}9", 1, 500)
0::multiLongPress("0", "{Blind}0", "{Blind})", 1, 500)
+0::multiLongPress("0", "{Blind+})", "{Blind+}0", 1, 500)
; ====================================== PUNCTUATION ======================================
-::multiLongPress("-", "{Blind}-", "{Blind}_", 1, 500)
+-::multiLongPress("-", "{Blind+}_", "{Blind+}-", 1, 500)
=::multiLongPress("=", "{Blind}=", "{Blind}+", 1, 500)
+=::multiLongPress("=", "{Blind+}+", "{Blind+}=", 1, 500)
[::multiLongPress("[", "{Blind}[", "{Blind}{", 1, 500)
+[::multiLongPress("[", "{Blind+}{", "{Blind+}[", 1, 500)
]::multiLongPress("]", "{Blind}]", "{Blind}}", 1, 500)
+]::multiLongPress("]", "{Blind+}}", "{Blind+}]", 1, 500)
\::multiLongPress("\", "{Blind}\", "{Blind}|", 1, 500)
+\::multiLongPress("\", "{Blind+}|", "{Blind+}\", 1, 500)

`;::multiLongPress("`", "{Blind}{Numpad0}", "{Blind})", 1, 500)
+`;::multiLongPress("`", "{Blind+})", "{Blind+}{Numpad0}", 1, 500)

'::multiLongPress("'", "{Blind}{Numpad9}", "{Blind}(", 1, 500)
+'::multiLongPress("'", "{Blind+}(", "{Blind+}{Numpad9}", 1, 500)

,::multiLongPress(",", "{Blind},", "{Blind}<", 1, 500)
+,::multiLongPress(",", "{Blind+}<", "{Blind+},", 1, 500)

.::multiLongPress(".", "{Blind}.", "{Blind}>", 1, 500)
+.::multiLongPress(".", "{Blind+}>", "{Blind+}.", 1, 500)
/::multiLongPress("/", "{Blind}/", "{Blind}?", 1, 500)
+/::multiLongPress("/", "{Blind+}?", "{Blind+}/", 1, 500)
`::multiLongPress("`", "{Blind}``", "{Blind}~", 1, 500)
+`::multiLongPress("`", "{Blind+}~", "{Blind+}``", 1, 500)
; ====================================== ADDITIONAL KEYS ======================================
CapsLock::BackSpace
*RAlt::modTap(ThisHotkey, "RAlt", "RControl", toggleLayer, "Qwerty")