#HotIf currentLayer = "directory"
; ====================================== LETTERS ======================================
q::toggleLayer(2)
w::toggleLayer(3)
e::toggleLayer(4)
; r::toggleLayer(5)
; t::toggleLayer(6)
; y::toggleLayer(7)
; u::toggleLayer(8)
; i::toggleLayer(9)
; o::toggleLayer(10)
; ; p::toggleLayer(0)
; a::toggleLayer(11)
; s::toggleLayer(12)
; d::toggleLayer(13)
; f::toggleLayer(14)
; g::toggleLayer(15)
; h::toggleLayer(16)
; j::toggleLayer(17)
; k::toggleLayer(18)
; l::toggleLayer(19)
; `;::toggleLayer(20)
; '::toggleLayer(21)
; ; z::toggleLayer(0)
; ; x::toggleLayer(0)
; c::toggleLayer(22)
; v::toggleLayer(23)
; b::toggleLayer(24)
; n::toggleLayer(25)
; m::toggleLayer(26)
; ,::toggleLayer(27)